name: msgpack_codable
version: 0.1.0
repository: https://github.com/blimster/msgpack_codable

environment:
  sdk: ^3.5.0-164.0.dev

dependencies:
  msgpack_dart: ^1.0.1
  json: ^0.20.1
  macros: ^0.1.0-main.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
