name: msgpack_codable
description: A library for encoding and decoding of the MessagePack format using the Dart macro feature. 
version: 0.1.0
repository: https://github.com/blimster/msgpack_codable
topics:
  - MessagePack
  - msgpack_dart
  - message serialization
  - macros

environment:
  sdk: ^3.5.0-243.0.dev

dependencies:
  msgpack_dart: ^1.0.1
  macros: ^0.1.0-main.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
